name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - run: npm ci
              working-directory: ./jules-extension

            - run: npm run compile
              working-directory: ./jules-extension

            - name: Install xvfb
              run: sudo apt-get install -y xvfb

            - run: xvfb-run -a npm test
              working-directory: ./jules-extension

            - name: Install vsce
              run: npm install -g @vscode/vsce

            - name: Package extension
              run: vsce package
              working-directory: ./jules-extension

            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload VSIX to Release
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./jules-extension/jules-extension-*.vsix
                  asset_name: jules-extension.vsix
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
